### ISSUE TITLE
[Bug Report] FS22 vehicleShader colorMats

### ISSUE THREAD

**Issue by Maaslandmods** [StjerneIdioten/I3D-Blender-Addon#146]
When selecting the FS22 vehicleShader in the Shader Source, only one Parameter appears with the title 'colorMat' instead of 'colorMat0', 'colorMat1', ect. 

Blender 2.93.6

FS19:
![2021-11-22 18_28_51-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/29893438/142907601-fcbcc322-a127-4c5c-b9cc-9757e64cc44c.png)

FS22:
![unknown](https://user-images.githubusercontent.com/29893438/142907406-ac25401d-4701-43c1-886d-5340930ca172.png)

**Comment by StjerneIdioten** [comment]
Giants have updated their shader spec from 4 to 5 and in the new spec it would seem that parameters can have an "arraySize" parameter, which determines that the parameter is an array of parameters. You then specify children of the parameter with default values for the indexes.

FS19, Shader Version 4:
![image](https://user-images.githubusercontent.com/11218511/142919938-9d9df9e0-ab65-476b-9e95-e1bd56ba996e.png)

FS22, Shader Version 5:
![image](https://user-images.githubusercontent.com/11218511/142920040-26520b7b-9fd8-4e3f-b612-2a324fbbe5d9.png)

The fix is easy enough, but the new version of the exporter should probably be able to tackle different shader versions.
