### ISSUE TITLE
[Bug Report] Deleting EmptySpace in XML after exporting i3dMappings

### ISSUE THREAD

**Issue by nilBrain** [StjerneIdioten/I3D-Blender-Addon#185]
After exporting, empty lines of the XML are deleted, even outside the 'i3dMappings' section, and tabs become 2x specCharacter...

**Comment by StjerneIdioten** [comment]
Could you provide an example? :-)

**Comment by nilBrain** [comment]
Befor export:

![Bild_2023-10-11_181821984](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/46376130/4e9cce78-6553-410c-80db-b4111b92621f)


After:
![Bild_2023-10-11_181912868](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/46376130/cefd6ca6-3365-4a9e-ac5c-ae73dcf7afba)

**Comment by StjerneIdioten** [comment]
That shows the spaces have been altered, but what about the tabs you are talking about?

**Comment by StjerneIdioten** [comment]
Anyway, I will see what I can do about it. Right now I am treating the files as XML (which they sort of are) and using Pythons xml libraries, but the problem is that the GE files really aren't proper xml files (xml is not supposed to be modified by humans). So none of the libraries respect any of the formatting. But I guess I will just have to do a dumb text replace instead.
