### ISSUE TITLE
[Bug Report] Splittype value not exported 

### ISSUE THREAD

**Issue by Sablerock1** [StjerneIdioten/I3D-Blender-Addon#188]
I’m creating new trees for fs22. When I enter splittype number in tab, like splittype=7, your exporter does nothing with it. There’s no message in log either.
Then I must open xml and add it manually. Why? If there’s problems with geometry, then put clear messages in log why SPLITTYPE cannot be processed. Pls!!

**Comment by StjerneIdioten** [comment]
Firstly, there is a reason why there is a template once you click to create a bug report. Contrary to your belief, that reason is NOT to just blatantly ignore everything it says and then proceed to write about how I should be handling log messages instead of providing any actual information to help me recreate the issue. If I can build this whole thing in my spare time to help guys like you out, then I believe you can survive having to manually edit one xml file for a little bit and also be a bit nicer to me when reporting issues 😉 

Secondly (and not surprisingly) I tried out the meager information you did provide by putting in a split type of 7 and I cannot reproduce the issue. Here, let me show you:
![image](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/11218511/00103da8-0cad-4205-9e5c-75f865583d8a)
![image](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/11218511/8fa47073-e481-428e-afd8-be8624e85d70)

Now if it is some specific case that leads to this then would you kindly put some more information for me to work with? Like for example a minimal example in Blender or some pictures 😃

**Comment by StjerneIdioten** [comment]
@Sablerock1 any more input on this?

**Comment by StjerneIdioten** [comment]
I can't reproduce this error and the reporter is not answering
