### ISSUE TITLE
VertexColors are not exported

### ISSUE THREAD

**Issue by nilBrain** [StjerneIdioten/I3D-Blender-Addon#204]
VertexColors are not exported to the i3d

Blender File in the Attachment

[staticLight.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/14574885/staticLight.zip)

**Comment by ssnd292** [comment]
@StjerneIdioten The issue here is that now since Colors are part of the data attribute system, they need to be setup extremely specific as its not "Vertex Color" Attribute, but "Face Corners Byte Colors". 

Only then it works.
![2024-03-12 21_05_43-](https://github.com/StjerneIdioten/I3D-Blender-Addon/assets/3914410/6f2d486a-13c5-4a37-87d7-d6ef411a2303)
