### ISSUE TITLE
Vertex color?

### ISSUE THREAD

**Issue by kbrandwijk** [StjerneIdioten/I3D-Blender-Addon#25]
**Describe the bug**
I switched from the original version this one was forked from to his version, and I noticed vertex colors are no longer exported. Is there an ETA for this feature? Thank you!

**Comment by StjerneIdioten** [comment]
It is more or less just an oversight on my part. I've been busy getting some of the other features implemented. Color is probably one of the easiest things to get going.

**Comment by kbrandwijk** [comment]
No problem, I had never looked at either the old codebase, or your rewrite codebase, until after submitting the issue. And yes, it did turn out to be something that could be very easily added ;)

**Comment by StjerneIdioten** [comment]
Going through the old codebase (which is horrendous) is luckily something I have to do quite seldomly by now, since most of the features from that has been implemented in my new edition. But I did give it a quick spin to see how it was done previously and concluded that it would be easy :P

**Comment by StjerneIdioten** [comment]
You say that you noticed that the feature was no longer supported, does this mean that you have used it in the old exporter? Because from my current testing it seems that the old exporter (NLD 2.8 conversion) does in fact not export the vertex colours correctly. The colors get exported, but they show up at the wrong vertices.

**Comment by StjerneIdioten** [comment]
I figured out the problem.
Both your fix and the old addon code uses the vertex_index to index into the mesh.vertex_colors collection, which is wrong. Per the blender docs it should be the loop_index.
The error was hard to spot because both loop_index and vertex_index have the same span. So you would never get and index error, but just get weird indexing of the vertex colors.

**Comment by kbrandwijk** [comment]
Thanks for figuring that out, I didn't have any time yet to circle back to it. I'm personally using this in an adapted version of your exporter where the vertex has a named vertex_color, so I didn't run into the error either.

**Comment by StjerneIdioten** [comment]
No problem, it was a planned feature under any circumstance. And if you have any other features you want included just throw em' in the issue tracker ;)

**Comment by kbrandwijk** [comment]
Yeah, I'll throw some random thoughts in there, might even pick up one or another if that suits you.
