### ISSUE TITLE
Path to material Shader and Variation should be editable in Blender

### ISSUE THREAD

**Issue by ssnd292** [StjerneIdioten/I3D-Blender-Addon#3]
Currently when exporting you have to set the shader and its variation type per material, which can become timeconsumin if you have several different materials per object, since you have to redo that step everytime you re-export the i3d file.

It would be more convenient to give materials parameters like "Shader Type" and "Shader Variation" so that the task of doing it by hand everytime after export is skipped.

For that, a relative pathing from the users Game library is needed to find the correct shader in the /data/shared/shaders folder

**Comment by StjerneIdioten** [comment]
This needs to get into the i3d file somehow:
![image](https://user-images.githubusercontent.com/11218511/84578719-3ad01000-adc8-11ea-8661-5c44cfbf78da.png)

**Comment by kbrandwijk** [comment]
Oh that would be a HUGE timesaver on iterative export-test-change-export cycles!

**Comment by kbrandwijk** [comment]
Additionally, it would be great if you could add a parameter dictionary as well (name and value).

**Comment by StjerneIdioten** [comment]
I am gonna do a filepicker that automatically opens to the '$data/shaders' folder, since this i where most people will get their shaders from. The entire export system is setup in a way that any file that gets exported (They all inherit from a base file class) is automatically checked for whether or not the path is relative to the fs data folder and does the proper '$data' replacement automatically.

And for 'parameter dictionary' do you mean those 'user attributes' you can set or just the parameters for whatever shader you have selected? Because in the former cause you should just create a new issue for that, since there isn't actually one. And in the latter case I am gonna deduce all parameters shown in the UI based on whatever shader file you pick( at least that is the plan)

**Comment by kbrandwijk** [comment]
I meant the parameters _for the shader_, if you read them from the shader XML, that would be awesome. I'm not really sure what you mean with 'user attributes'.

**Comment by StjerneIdioten** [comment]
You can specify sort of custom parameters per scene object in GE. The menu is called "User attributes" inside of GE :-)

**Comment by kbrandwijk** [comment]
Oh right, yes, but that has nothing to do with shaders/materials indeed.

**Comment by StjerneIdioten** [comment]
5fcff74dbe9f772aa7b163ccabf861b4e63f9ad3 is the last commit in a string of commits that implements this functionality. Documentation will follow on the wiki.

**Comment by StjerneIdioten** [comment]
I will close this for now as the feature has been implemented. I will keep a list going here of potential enhancements for the feature.

- Limits for parameters read from shader file
