### ISSUE TITLE
Exporting Several Meshes at once will only apply one material to all of them in i3d

### ISSUE THREAD

**Issue by ssnd292** [StjerneIdioten/I3D-Blender-Addon#36]
**Describe the bug**
If you have several unmerged meshes with different materials applied to them in Blender and export them to i3d, the exporter only applies a single material to all other meshes.

It seems it only reads and applies the first mesh in thats exported (in my case the 03_Cube)

Expected behavior would be the correct export from all materials applied to the correct meshes.

[MultiMaterialExport.zip](https://github.com/StjerneIdioten/I3D-Blender-Addon/files/4398871/MultiMaterialExport.zip)

**Comment by StjerneIdioten** [comment]
Hmm, this is strange. Looking through the i3d file I see the following: 
![image](https://user-images.githubusercontent.com/11218511/83958028-6bb2c100-a86d-11ea-8590-90e4c20fe03a.png)
![image](https://user-images.githubusercontent.com/11218511/83958030-740afc00-a86d-11ea-9bc6-356a5a8de354.png)

But inside of GE they are all sharing the same material for some reason? There are no errors in the import log of GE or anything, this is very strange.

**Comment by StjerneIdioten** [comment]
I just tested it. Turns out that it isn't anything to do with the exporter. I tried changing one material and GE would then use both materials. So it seems that if you have two (or more) identical materials, but with different names, GE will just ignore the fact that they are two different materials and just use whichever material it encountered first for all objects that might have used a "twin" material.

I am closing this and filing it under Giants Engine Quirks :-)
