### ISSUE TITLE
Change castsShadows and receiveShadows by default true

### ISSUE THREAD

**Issue by SuguruGT** [StjerneIdioten/I3D-Blender-Addon#70]
Meshes are usually mostly with the value true for the castsShadows and receiveShadows attributes.
It would be very useful if the default setting was true and not false, as is now set for the distanceBlending attribute.
Thank you.

**Comment by ssnd292** [comment]
While this is true I'd wager against pre-setting such values for users. While it is handy I would not set to anything that it would not be default in GE.

**Comment by StjerneIdioten** [comment]
Yeah, those values are going to stay false. Settings in general are gonna follow whatever default there is in GE, which in this case means that they are off by default.

But, do not fret. I think #34 will take care of your problem once that gets implemented ;-)

**Comment by SuguruGT** [comment]
The 3d shapes of GE have different default values because these 3d shapes have a different use. For this reason, for this exporter is much better off not following GE for its general default settings.
#34 we see the predefined presets with more variables but there are no these two variables. You can see it from the pictures.
If you implement #34 as maya there will be no changes for these two variables. Maya is the alternativa of this exporter and this demand should go in the same direction of the settings that the exporter of maya has.
The maya exporter exports 3d shapes by setting these two variables to true by default and distanceBlending does not have a default value.
We think our request will be very useful to facilitate the work of all modding teams. We hope you reevaluate your decision.

**Comment by StjerneIdioten** [comment]
Well, I will stick to following the defaults of the I3D format itself, which means that those are toggled off by default. 
When the user presets come around, and they will, this will no longer be a problem in any way. And no, I am not just gonna blindly follow the implementation of how it is in Maya.
The Maya exporter is mostly used as **inspiration** for features, since the blender exporter has been neglected for so long that it isn't even worth grabbing ideas from.
For the user presets I will gather a collection of the most important presets that should come pre-done with the exporter and in theory I could allow people to define their own presets (that are saved in the addon) if that is useful in any way.

I can give you a hint though, to how you can actually do things a bit easier in blender than going from object to object and toggling those settings. Because all of the i3d attributes are actually just normal blender properties, which means you can do with them as you would any other property.

So if you select all of your objects, change the settings to enabled and then `right-click` -> `Copy to Selected`, it will copy that setting to every object you have selected. [This gif I made shows the process](https://jmp.sh/8Vl8rAt)

I hope this makes your life a little bit easier until I implement presets ;-)

**Comment by SuguruGT** [comment]
Ok.
Thank you.
