### ISSUE TITLE
Exporter deletes comments in xml file

### ISSUE THREAD

**Issue by SgtRoyal** [StjerneIdioten/I3D-Blender-Addon#74]
The exporter kills all comments in the xml file, no matter the location of them.

Before:
![image](https://user-images.githubusercontent.com/72036238/94460313-d0957c80-01b8-11eb-8ef9-6ad801cf20f3.png)

After export:
![image](https://user-images.githubusercontent.com/72036238/94460362-e73bd380-01b8-11eb-96b7-ac869bbbfe0a.png)

Tested on Exporter **Version 1.2.0**

**Comment by StjerneIdioten** [comment]
Just a little comment, if you check the blender console after exporting, it will tell you the exact version number used for the exporter ;-) Because version 1.2.0 can be many versions since currently it is a development version with an extra tag added.

I have verified the bug and I will implement a fix shortly. This relates back to #54 as other xml libraries parses comments per standard.
